#!/bin/bash

# BOOTLOADER
# ============================================================================
# Here we install and configure Grub bootloader, all steps are described in
# official documentation: https://wiki.archlinux.org/index.php/GRUB
# We also install additional themes for beautifull OS selection menu.

_bootloader() {

    # Install Grub
    _info "Installing Grub for ${FIRMWARE} firmware"
    _chroot "pacman --noconfirm -S ${_bootapps}"

    # -- BIOS --
    _chroot "grub-install --target=i386-pc /dev/${_disk}"

    # Config Grub
    _info "Setting Grub for ${FIRMWARE} firmware"
    _chroot "grub-mkconfig -o /boot/grub/grub.cfg"
}
