#!/bin/bash

# SYSTEM APPLICATIONS
# ============================================================================

# Arch Linux
export _arch="base base-devel"

# Microcode (in case of Intel CPU)
export _intel="intel-ucode"

# Network
export _netapps="ntp networkmanager wget nmap rp-pppoe dhclient \
iw wpa_supplicant wireless_tools git gitolite exfat-utils rsnapshot qbs jenkins"

# Bootloader
export _bootapps="grub os-prober gptfdisk efibootmgr"
