#!/bin/bash

# SYSTEM APPLICATIONS
# ============================================================================

# Arch Linux
export _arch="base base-devel linux-firmware nano htop fail2ban"

# Kernel
export _default_kernel="linux"
export _hardened_kernel="linux-hardened"
export _lts_kernel="linux-lts"
export _zen_kernel="linux-zen"

# Microcode (in case of Intel CPU)
export _intel="intel-ucode"

# Network
export _netapps="ntp networkmanager wget nmap dhclient \
nginx openssl certbot certbot-nginx"

# Bootloader
export _bootapps="grub os-prober"
