#!/bin/bash

# SYSTEM APPLICATIONS
# ============================================================================

# Arch Linux
export _arch="base linux nano htop fail2ban svn git openssl openssh openvpn mariadb rvm certbot certbot-nginx samba"

# Microcode (in case of Intel CPU)
export _intel="intel-ucode"

# Network
export _netapps="nginx redmine imagemagick gitolite jenkins"

# Bootloader
export _bootapps="grub os-prober"
